//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerTable
    {
        public string UserName { get; set; }
        public string Name { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public long PhoneNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string CardType { get; set; }
        public string SelectBank { get; set; }
        public string IFSC_Code { get; set; }
        public Nullable<long> AccountNumber { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual CardTypeTable CardTypeTable { get; set; }
        public virtual OTP_Validation OTP_Validation { get; set; }
    }
}
