//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP_Validation
    {
        public string UserName { get; set; }
        public Nullable<int> OTP_Sent { get; set; }
    
        public virtual ConsumerTable ConsumerTable { get; set; }
    }
}
